// prettier-ignore
export const adjectives = ["aaronic", "abased", "abashed", "abating", "abaxial", "abeyant", "abiding", "abiotic",
  "abject", "ablated", "ablaze", "able", "abler", "ablest", "abloom", "ablush", "aboral", "about", "above", "abraded",
  "abreast", "abroach", "abroad", "abrupt", "absent", "absurd", "abusive", "abuzz", "abysmal", "abyssal", "acadian",
  "acarid", "acarine", "acaroid", "acaudal", "accrete", "accrued", "accurst", "ace", "acerate", "acerb", "acerbic",
  "acetic", "acetose", "acetous", "achaean", "aching", "achy", "acid", "acidic", "aciform", "acinose", "acinous",
  "acold", "acorned", "acred", "acrid", "across", "acrylic", "actable", "actinal", "acting", "actinic", "active",
  "actual", "acute", "acyclic", "adagio", "adam", "adamant", "adamic", "adapted", "adaxial", "added", "addle",
  "addled", "adenoid", "adept", "adipose", "adjunct", "admired", "adnate", "adonic", "adopted", "adored", "adoring",
  "adorned", "adrenal", "adrift", "adroit", "adult", "adunc", "adust", "advance", "adverse", "advised", "aegean",
  "aeneous", "aeolian", "aeolic", "aeonian", "aerated", "aerial", "aery", "afeard", "afeared", "affable", "affine",
  "affined", "affixed", "afghan", "afghani", "afire", "aflame", "afloat", "afoot", "afoul", "afraid", "afric",
  "african", "aft", "after", "aftmost", "agamic", "agamid", "agamous", "agape", "agaze", "aged", "agee", "ageing",
  "ageless", "agelong", "aghast", "agile", "aging", "agitato", "agleam", "agley", "aglow", "agnate", "agnatic", "ago",
  "agog", "agone", "agonic", "agravic", "agreed", "aground", "aguish", "ahead", "ahorse", "ahull", "aided", "aidful",
  "aidless", "ailing", "aimless", "ain", "air", "aired", "airier", "airiest", "airless", "airsick", "airy", "aisled",
  "ajar", "akimbo", "akin", "alar", "alarmed", "alary", "alaskan", "alate", "alated", "albinic", "albitic", "alcaic",
  "aldine", "alert", "alexic", "algal", "algid", "algoid", "alien", "aliform", "alight", "aligned", "alined",
  "aliped", "aliquot", "aliunde", "alive", "all", "alleged", "allegro", "allied", "allowed", "alodial", "aloetic",
  "alone", "aloof", "alpha", "alpine", "alright", "alt", "altaic", "altered", "altern", "alto", "alvine", "amateur",
  "amative", "amatory", "amazed", "amazing", "amber", "ambery", "ambient", "amebic", "ameboid", "amended", "amental",
  "amharic", "amiable", "amish", "amiss", "amnesic", "amoebic", "amok", "amoral", "amoroso", "amorous", "amort",
  "ample", "ampler", "amplest", "amuck", "amused", "amusing", "amusive", "amyloid", "anaemic", "ancient", "andante",
  "andean", "andorra", "android", "ane", "anemic", "angelic", "angered", "angevin", "anginal", "angled", "anglian",
  "angrier", "angry", "anguine", "angular", "anile", "animal", "animate", "animist", "anionic", "annelid", "annual",
  "annular", "anodal", "anodic", "anodyne", "anoetic", "anomic", "another", "anoxic", "ansate", "ant", "antacid",
  "ante", "anti", "antic", "antique", "antiwar", "anurous", "anxious", "any", "aortal", "aortic", "apart", "apeak",
  "aphasic", "aphetic", "aphonic", "aphotic", "apian", "apical", "apodal", "apodous", "apogeal", "apogean", "applied",
  "apropos", "apsidal", "apt", "apteral", "aqua", "aquatic", "aqueous", "arabian", "arabic", "arable", "aragon",
  "aramaic", "aran", "arc", "arcane", "arced", "arch", "archaic", "arched", "arching", "arctic", "arcuate", "ardent",
  "arduous", "areal", "argent", "argive", "arguing", "argyle", "arian", "arid", "armed", "armless", "aroid", "arow",
  "arrant", "arrased", "arrowy", "artful", "artier", "artiest", "artless", "arty", "ascetic", "ascitic", "aseptic",
  "ashake", "ashamed", "ashen", "ashier", "ashiest", "ashy", "asian", "asianic", "asiatic", "asinine", "askance",
  "askant", "askew", "asking", "aslant", "asleep", "aslope", "asocial", "aspen", "asphalt", "asprawl", "asquint",
  "astable", "astatic", "astir", "astral", "astute", "astylar", "asunder", "aswarm", "atactic", "ataxic", "atheism",
  "atheist", "athirst", "athrill", "atilt", "atingle", "atomic", "atomism", "atonal", "atonic", "atrial", "atrip",
  "attack", "attent", "attic", "attired", "attrite", "attuned", "auburn", "audible", "audient", "audile", "augean",
  "augitic", "augural", "august", "auld", "aulic", "aural", "aureate", "auric", "auroral", "aurous", "austere",
  "austral", "autumn", "auxetic", "average", "averse", "avestan", "avian", "avid", "avionic", "avocado", "avowed",
  "avulsed", "awaited", "awake", "aware", "awash", "away", "aweary", "awed", "aweless", "awesome", "awful", "awheel",
  "awing", "awned", "awnless", "awny", "awol", "awry", "axial", "axile", "aymaran", "azilian", "azoic", "azonal",
  "azonic", "azotic", "aztec", "aztecan", "azure", "azygos", "azygous", "babist", "baby", "babyish", "baccate",
  "bacchic", "back", "backed", "bad", "baddish", "baffled", "baggier", "baggy", "bahai", "bairnly", "baked", "baking",
  "bald", "balding", "baldish", "baleful", "balkan", "balked", "balkier", "balking", "balky", "balled", "bally",
  "balmier", "balmy", "balneal", "balsamy", "baltic", "baluchi", "bamboo", "bananas", "banded", "bandy", "baneful",
  "bangled", "banned", "banner", "bantam", "bantu", "baptist", "bar", "barbate", "barbed", "bardic", "bardy", "bare",
  "bared", "barer", "barest", "baric", "baring", "barish", "barkier", "barky", "barmier", "barmy", "baroque",
  "barred", "barren", "barytic", "basal", "base", "based", "baser", "basest", "bashful", "basic", "basilar", "bated",
  "bathyal", "bats", "battier", "battled", "batty", "batwing", "bausond", "bawdier", "bawling", "bay", "beached",
  "beachy", "beaded", "beadier", "beady", "beaked", "beaky", "beamier", "beaming", "beamish", "beamy", "bearded",
  "bearing", "bearish", "beastly", "beat", "beaten", "beating", "beauish", "beaut", "bedded", "bedewed", "bedfast",
  "bedight", "bedrid", "beechen", "beefier", "beefy", "beerier", "beery", "beetle", "behind", "beige", "belated",
  "belgian", "belgic", "bellied", "beloved", "belted", "bemazed", "bemused", "ben", "bended", "bending", "bendy",
  "benefic", "bengali", "bent", "bentham", "benthic", "benzal", "benzoic", "berber", "bereft", "bermuda", "berried",
  "berserk", "bespoke", "best", "bestead", "bested", "better", "betting", "bevel", "beveled", "bhutan", "biafran",
  "bias", "biased", "biaxal", "biaxial", "bibbed", "bicorn", "bifid", "bifilar", "bifocal", "bifold", "biform", "big",
  "bigger", "biggest", "biggish", "bigoted", "bihari", "bijou", "bilgier", "bilgy", "biliary", "bilious", "billed",
  "billion", "billowy", "bilobed", "bimodal", "binary", "binate", "binding", "bionic", "biotic", "biped", "bipedal",
  "bipolar", "birch", "birchen", "birk", "birken", "bistred", "bit", "biting", "bitless", "bitonal", "bitten",
  "bitter", "bitty", "bivalve", "bizarre", "bizonal", "black", "bladed", "blae", "blah", "blame", "blamed", "bland",
  "blank", "blanket", "blaring", "blasted", "blatant", "blate", "blazing", "bleak", "blear", "bleary", "blended",
  "blessed", "blest", "blind", "blinded", "blithe", "bloated", "blocked", "blocky", "blond", "blonde", "blooded",
  "bloomed", "bloomy", "blotchy", "blotto", "blotty", "blowier", "blown", "blowsy", "blowy", "blowzed", "blowzy",
  "blubber", "blue", "bluer", "bluest", "bluff", "bluish", "blunt", "blunted", "blurred", "blurry", "boarish",
  "bobbery", "bobs", "bobtail", "bodger", "bodied", "boding", "boggy", "bogus", "boiled", "boiling", "bold",
  "bolshie", "bolshy", "bolted", "bomb", "bond", "bonded", "bone", "bonier", "boniest", "bonism", "bonkers", "bonnie",
  "bonnier", "bonny", "bony", "bonzer", "booked", "bookish", "booming", "boon", "boorish", "booted", "bootleg",
  "boozier", "boracic", "boreal", "bored", "boric", "boring", "born", "bosker", "boskier", "bosky", "bosnian",
  "bosom", "bosomed", "boss", "bossier", "bossy", "botanic", "botched", "botchy", "both", "bottom", "bought",
  "bouilli", "boulle", "bouncy", "bound", "bounded", "bounden", "bousy", "bovid", "bovine", "bow", "bowed", "bowery",
  "bowing", "boxed", "boxy", "boyish", "braced", "bracing", "brag", "braided", "brainy", "braised", "braky",
  "braless", "brambly", "branchy", "branded", "branny", "brash", "brashy", "bratty", "brave", "braver", "bravest",
  "braving", "braw", "brawny", "brazen", "breathy", "breezy", "brick", "brickle", "bricky", "bridal", "brief",
  "briery", "bright", "brimful", "brinded", "brindle", "brinier", "brinish", "briny", "brisk", "bristly", "british",
  "brittle", "broad", "broch", "broiled", "broke", "broken", "bromic", "bronze", "bronzed", "bronzy", "brood",
  "broody", "broomy", "brother", "brown", "browned", "browny", "bruised", "brumal", "brumous", "brunet", "brushed",
  "brushy", "brusque", "brut", "brutal", "brute", "brutish", "bubbly", "bubonic", "buccal", "buck", "bucked",
  "buckish", "buckram", "bucolic", "budding", "budless", "buff", "bugged", "buggy", "bugs", "buhl", "built",
  "buirdly", "bulbar", "bulbed", "bulbous", "bulging", "bulgy", "bulimic", "bulk", "bulkier", "bulky", "bull",
  "bullate", "bulldog", "bullied", "bullish", "bully", "bum", "bumper", "bumpier", "bumpy", "bunched", "bunchy",
  "bunted", "buoyant", "burghal", "buried", "burked", "burled", "burlier", "burly", "burman", "burmese", "burned",
  "burning", "burnt", "burred", "burrier", "burry", "bursal", "burst", "bush", "bushed", "bushier", "bushy", "busied",
  "busier", "busiest", "busked", "bust", "busted", "bustier", "bustled", "busty", "busy", "busying", "butch",
  "buttery", "buttony", "butyric", "buxom", "buyable", "buzzing", "bye", "bygone", "byronic", "byssal", "byssoid",
  "cabbagy", "cabinet", "caddish", "cade", "cadent", "cadgy", "caecal", "cagier", "cagiest", "cagy", "cairene",
  "cairned", "caitiff", "calando", "calced", "calcic", "calico", "called", "caller", "callous", "callow", "calm",
  "calming", "calmy", "caloric", "calved", "cambial", "cameral", "camp", "campy", "canary", "candent", "candid",
  "candied", "canine", "canned", "cannier", "canny", "canonic", "canopic", "cant", "canted", "canty", "cany",
  "capable", "caped", "capital", "capped", "caprine", "capsian", "captive", "carabid", "caramel", "cardiac",
  "careful", "caring", "carious", "carking", "carlish", "carmine", "carnal", "carnose", "carotid", "carpal",
  "carping", "carroty", "carsick", "carved", "carven", "cased", "caseous", "cashed", "caspian", "cast", "castled",
  "castor", "casual", "catalan", "catchy", "cattish", "catty", "caudal", "caudate", "cauld", "cauline", "caulked",
  "causal", "caustic", "cecal", "cedar", "cedarn", "celiac", "celsius", "celtic", "censual", "center", "central",
  "centred", "centric", "centum", "ceramic", "cerated", "cercal", "cereal", "cered", "cereous", "ceric", "cerise",
  "certain", "cervid", "cervine", "cestoid", "cesural", "chad", "chadic", "chafed", "chaffy", "chained", "chalky",
  "chance", "chancy", "changed", "chanted", "chaotic", "chapped", "charged", "charier", "charmed", "charnel",
  "charry", "chary", "chasmal", "chasmed", "chasmic", "chasmy", "chaste", "chaster", "chatty", "cheap", "checked",
  "checky", "cheek", "cheeked", "cheeky", "cheerly", "cheery", "cheesed", "cheesy", "chelate", "chemic", "chequy",
  "cherry", "cherty", "chesty", "chewier", "chewy", "chian", "chic", "chichi", "chicken", "chief", "chiefly",
  "chiffon", "childly", "chilean", "chill", "chilled", "chilly", "chin", "china", "chinese", "chintzy", "chipped",
  "chipper", "chippy", "chirk", "chirpy", "chloric", "chocker", "choice", "choicer", "choked", "chokey", "chokier",
  "choking", "choky", "chomsky", "choosey", "choosy", "chopped", "choppy", "choral", "chordal", "choroid", "chosen",
  "chromic", "chronic", "chubby", "chuffy", "chummy", "chunky", "churchy", "chymous", "cichlid", "ciliary", "ciliate",
  "cindery", "circean", "cirrate", "cirrose", "cirsoid", "cissoid", "cissy", "cisted", "cistic", "citable", "citric",
  "citrous", "citrus", "civic", "civil", "clad", "clamant", "clammy", "clarino", "clarion", "clastic", "clausal",
  "clavate", "clawed", "clayey", "clayish", "clean", "cleaned", "cleanly", "clear", "cleared", "cleft", "clement",
  "clerkly", "clever", "cliffy", "clingy", "clipped", "cliquey", "cliquy", "cloacal", "cloaked", "cloddy", "clogged",
  "cloggy", "clonal", "clonic", "close", "closed", "closer", "closest", "closet", "closing", "clothed", "clotted",
  "clotty", "clouded", "cloudy", "cloven", "clovery", "cloying", "clubby", "clucky", "clumpy", "clumsy", "clunky",
  "clupeid", "clypeal", "cnemial", "coalier", "coaly", "coastal", "coated", "coaxial", "coaxing", "coccal", "coccoid",
  "coconut", "cod", "coddled", "coeliac", "coequal", "coeval", "cogent", "cogged", "cognate", "coiled", "coiling",
  "cold", "coldish", "colicky", "collect", "colloid", "colly", "colonic", "color", "colored", "colory", "colour",
  "coltish", "comal", "comate", "combed", "combust", "comedic", "comely", "cometic", "comfier", "comfy", "comic",
  "comical", "coming", "commo", "common", "comose", "compact", "complex", "compo", "compony", "comtian", "comtist",
  "concave", "conchal", "conched", "concise", "condign", "conic", "conical", "connate", "conoid", "content", "convex",
  "convict", "cooing", "cooked", "cooking", "cool", "cooled", "cooling", "coolish", "copepod", "copied", "copious",
  "coppery", "coptic", "coral", "cordate", "corded", "cordial", "corked", "corkier", "corking", "corky", "cormous",
  "corneal", "corned", "cornier", "cornish", "cornual", "cornute", "corny", "coronal", "correct", "corrupt",
  "corvine", "cosher", "cosier", "cosies", "cosiest", "cosmic", "costal", "costate", "costive", "costly", "costume",
  "cosy", "cottony", "counter", "country", "county", "couped", "coupled", "courant", "coursed", "courtly", "couth",
  "couthie", "couthy", "covered", "covert", "coveted", "coward", "cowed", "cowled", "coxal", "coy", "coyish",
  "cozier", "coziest", "cozy", "crabbed", "crabby", "crack", "cracked", "crackle", "crackly", "crafty", "cragged",
  "craggy", "cramped", "cranial", "crank", "cranky", "crash", "craved", "craven", "crawly", "crazed", "crazier",
  "crazy", "creaky", "cream", "creamy", "creased", "creasy", "credal", "credent", "creedal", "creepy", "crenate",
  "creole", "cressy", "crested", "cretan", "cricoid", "crimean", "crimpy", "crimson", "crinal", "crined", "crinite",
  "crinkly", "crinoid", "crinose", "criollo", "crisp", "crispy", "croaky", "croat", "crocked", "crocus", "cronk",
  "crook", "crooked", "cropped", "cross", "crossed", "croupy", "crouse", "crowded", "crowing", "crowned", "crucial",
  "crude", "cruder", "crudest", "cruel", "crumb", "crumbly", "crumby", "crummy", "crunchy", "crural", "crushed",
  "crustal", "crusted", "crusty", "crying", "cryptal", "cryptic", "crystal", "ctenoid", "cuban", "cubbish", "cubic",
  "cubical", "cubist", "cubital", "cuboid", "cuddly", "cuffed", "cufic", "culicid", "cultic", "cultish", "cuneal",
  "cuneate", "cupped", "cuprous", "cur", "curable", "curbed", "curdier", "curdled", "curdy", "cured", "curious",
  "curled", "curlier", "curling", "curly", "current", "currish", "cursed", "cursing", "cursive", "cursory", "curst",
  "curt", "curtal", "curtate", "curule", "curved", "curvier", "curving", "curvy", "cushy", "cuspate", "cusped",
  "cussed", "custom", "cut", "cutcha", "cute", "cuter", "cutest", "cutting", "cutty", "cyan", "cyanic", "cyclic",
  "cycloid", "cyclone", "cymoid", "cymose", "cymric", "cynic", "cynical", "cyprian", "cypriot", "cystic", "cystoid",
  "cytoid", "czarist", "czech", "dabbled", "dada", "daedal", "daffier", "daffy", "daft", "daily", "daimen", "dainty",
  "daisied", "dam", "damaged", "damask", "damfool", "damp", "dancing", "dandy", "dang", "danged", "danish", "dank",
  "dantean", "dapper", "dapple", "dappled", "dardic", "daring", "dark", "darkish", "darling", "darn", "darned",
  "darting", "dash", "dashed", "dashing", "datable", "dated", "datival", "dative", "daubed", "dauby", "daunted",
  "daylong", "daytime", "dazed", "dead", "deadly", "deaf", "deal", "dear", "deathly", "deathy", "debased", "decadal",
  "decani", "decapod", "decent", "decided", "decimal", "decked", "deckled", "decreed", "decuple", "dedal", "deep",
  "defaced", "defiant", "defiled", "defined", "deft", "defunct", "degree", "deictic", "deific", "deiform", "deism",
  "deistic", "deject", "delian", "delible", "delphi", "delphic", "deltaic", "deltoid", "demoded", "demotic", "demure",
  "demurer", "denary", "dense", "denser", "densest", "dental", "dentate", "dented", "dentoid", "denuded", "deontic",
  "deposed", "deputy", "dere", "derived", "dermal", "dermic", "dermoid", "dern", "dernier", "descant", "desert",
  "desired", "desktop", "desmoid", "deuced", "deviant", "deviate", "deviled", "devious", "devoid", "devoted",
  "devout", "dewy", "dexter", "dextral", "diacid", "diarch", "diazo", "dibasic", "dicey", "diet", "dietary",
  "diffuse", "dighted", "digital", "diglot", "dilated", "diluent", "dilute", "diluted", "dim", "dime", "dimmed",
  "dimmest", "dimming", "dimply", "dinge", "dingier", "dingy", "diplex", "diploid", "dipnoan", "dipolar", "dipped",
  "dippier", "dippy", "dire", "direct", "direful", "direr", "direst", "dirt", "dirtier", "dirty", "discoid", "dished",
  "dishy", "dismal", "distal", "distant", "distent", "distyle", "disused", "diurnal", "divers", "diverse", "divided",
  "divine", "dizzied", "dizzier", "dizzy", "doable", "docile", "docked", "doddery", "dodgy", "dogged", "doggish",
  "doggone", "doggy", "doiled", "doited", "dolce", "doleful", "dollish", "doltish", "domed", "domical", "donated",
  "done", "donnard", "donnish", "donsie", "doomed", "doped", "dopey", "dopier", "dopiest", "dopy", "dorian", "doric",
  "dormant", "dormie", "dormy", "dorsal", "dorty", "dosed", "dotal", "dotier", "dotiest", "doting", "dotted",
  "dottier", "dotty", "doty", "double", "doubled", "douce", "doughty", "doughy", "dour", "dovish", "dowdy", "dowered",
  "dowf", "dowie", "down", "downed", "downier", "downy", "dozen", "dozenth", "dozier", "doziest", "dozing", "dozy",
  "drab", "draffy", "drafty", "draggy", "drained", "drastic", "dratted", "drawn", "dread", "dreaded", "dreamed",
  "dreamy", "drear", "dreary", "dree", "dreggy", "dresden", "dress", "dressed", "dressy", "dried", "drier", "driest",
  "drifty", "drilled", "drippy", "driven", "driving", "drizzly", "droll", "droning", "dronish", "droopy", "dropped",
  "drossy", "drouthy", "drowned", "drowsy", "drugged", "druidic", "drumly", "drunk", "drunken", "drusian", "dry",
  "dryer", "drying", "dual", "dubious", "ducal", "duckie", "duckier", "ducky", "ductile", "dud", "duddy", "dudish",
  "due", "duff", "dulcet", "dull", "dulled", "dullish", "dulotic", "dumb", "dummy", "dumped", "dumpier", "dumpy",
  "dun", "dungy", "dunked", "duple", "duplex", "durable", "dural", "dure", "dusk", "duskier", "duskish", "dusky",
  "dustier", "dusty", "dutch", "duteous", "dutiful", "dwarf", "dyable", "dyadic", "dyeable", "dyeline", "dying",
  "dynamic", "dysuric", "each", "eager", "eared", "earless", "earlier", "early", "earned", "earnest", "earthen",
  "earthly", "earthy", "eased", "easeful", "easier", "easiest", "east", "eastern", "easy", "eatable", "eaten", "eath",
  "eating", "ebb", "ebon", "ebony", "ecbolic", "eccrine", "echoic", "echoing", "echt", "ecru", "ectopic", "ectypal",
  "edaphic", "eddic", "edenic", "edental", "edge", "edged", "edgier", "edgiest", "edging", "edgy", "edible",
  "edictal", "edified", "edited", "eely", "eerie", "eerier", "eeriest", "eery", "effable", "effete", "effuse", "egal",
  "eidetic", "eight", "eighth", "eighty", "eild", "eirenic", "elamite", "elapsed", "elastic", "elated", "elating",
  "elative", "elder", "elderly", "eldest", "eleatic", "elect", "elected", "elegant", "elegiac", "eleven", "elfin",
  "elfish", "elite", "elmier", "elmiest", "elmy", "else", "elusive", "eluvial", "elvish", "elysian", "elzevir",
  "emanant", "embolic", "embowed", "embryo", "emended", "emersed", "emetic", "eminent", "emotive", "empiric",
  "emptied", "empties", "empty", "emulous", "enate", "encased", "endarch", "ended", "endemic", "endless", "endmost",
  "endowed", "endways", "enemy", "engaged", "english", "enorm", "enough", "enow", "enraged", "enrapt", "ensuing",
  "enteral", "enteric", "entire", "entomic", "entopic", "enured", "envious", "eocene", "eolian", "eolic", "eozoic",
  "epaxial", "ephebic", "epic", "epical", "epicene", "epigeal", "epigene", "epizoan", "epizoic", "epoxy", "equable",
  "equal", "equine", "erased", "ergodic", "ericoid", "eristic", "ermined", "errable", "errant", "erratic", "errhine",
  "erring", "ersatz", "erse", "erudite", "escaped", "eskimo", "essive", "estival", "estrous", "etched", "eternal",
  "eterne", "etesian", "ethic", "ethical", "ethiop", "ethmoid", "ethnic", "etonian", "eustyle", "evasive", "even",
  "evens", "every", "evident", "evil", "evoked", "exact", "exalted", "exarate", "exarch", "excess", "excited",
  "excused", "exempt", "exhaled", "exigent", "exilic", "exotic", "expert", "expired", "exposed", "express", "exsert",
  "extant", "extinct", "extra", "extreme", "exuvial", "eyeless", "eyetie", "fab", "fabian", "fabled", "faced",
  "facete", "faceted", "facial", "facile", "factual", "facular", "fadable", "faddier", "faddish", "faddy", "faded",
  "fading", "faecal", "faerie", "faery", "failed", "failing", "fain", "faint", "fair", "fairish", "fairy", "fake",
  "falange", "falcate", "fallen", "falling", "fallow", "false", "falser", "falsest", "famed", "famous", "fanatic",
  "fancied", "fancy", "fanfold", "fanged", "fangled", "fanned", "far", "faradic", "farand", "faraway", "farci",
  "farm", "farming", "faroese", "farrow", "farther", "fascial", "fascist", "fast", "fat", "fatal", "fated", "fateful",
  "fatigue", "fatless", "fatter", "fattest", "fattier", "fattish", "fatty", "fatuous", "faucal", "faucial", "faulty",
  "faunal", "fauve", "faux", "favored", "fawning", "fay", "fazed", "feal", "fearful", "feat", "febrile", "fecund",
  "federal", "feeble", "feebler", "feeling", "feigned", "feisty", "feline", "fell", "felled", "fellow", "felon",
  "felsic", "felt", "felted", "female", "femoral", "fenian", "fenny", "feodal", "feral", "ferial", "ferine",
  "fernier", "ferny", "ferrety", "ferric", "ferrous", "fertile", "fervent", "fervid", "festal", "festive", "fetal",
  "fetial", "fetid", "feudal", "fevered", "few", "fewer", "fewest", "fey", "fezzed", "fibered", "fibroid", "fibrous",
  "fibular", "fickle", "fictile", "fictive", "fiddly", "fidgety", "fierce", "fiercer", "fierier", "fiery", "fifteen",
  "fifth", "fifty", "figural", "figured", "fijian", "filar", "filial", "filled", "filmed", "filmier", "filmy",
  "filose", "filthy", "finable", "final", "fine", "fined", "finer", "finest", "finical", "finicky", "finite",
  "finless", "finned", "finnic", "finnier", "finnish", "finny", "fired", "firm", "firry", "first", "fiscal",
  "fishier", "fishy", "fissile", "fistic", "fit", "fitchy", "fitful", "five", "fixable", "fixed", "fizzier",
  "fizzing", "fizzy", "flabby", "flaccid", "flaggy", "flakier", "flaky", "flamier", "flaming", "flamy", "flappy",
  "flared", "flaring", "flash", "flashy", "flat", "flaunty", "flawed", "flawier", "flawy", "flaxen", "flecked",
  "fledged", "fledgy", "fleecy", "fleeing", "fleet", "flemish", "fleshly", "fleshy", "fleury", "flexed", "flexile",
  "flighty", "flimsy", "flinty", "flip", "floaty", "floccus", "floppy", "floral", "florid", "flory", "flossy",
  "floury", "flowery", "flowing", "flown", "fluent", "fluffy", "fluid", "fluidal", "fluidic", "flukey", "flukier",
  "fluky", "fluoric", "flush", "flushed", "fluted", "flutier", "fluty", "fluvial", "fly", "flyable", "flyaway",
  "flying", "foaled", "foamier", "foaming", "foamy", "focal", "focused", "foetal", "foetid", "fogged", "foggier",
  "foggy", "fogless", "fogyish", "foiled", "fold", "folded", "folding", "foliar", "foliate", "folio", "foliose",
  "folk", "folkish", "folksy", "fond", "fontal", "fool", "fooling", "foolish", "footed", "footier", "forced", "fore",
  "foreign", "forfeit", "forged", "forked", "forkier", "forky", "forlorn", "formal", "formed", "former", "formic",
  "fornent", "forte", "fortis", "forty", "forward", "forworn", "foster", "fou", "foul", "fouled", "found", "founded",
  "four", "fourth", "foveal", "foveate", "foxier", "foxiest", "foxy", "fozier", "foziest", "fozy", "fragile", "frail",
  "framed", "frank", "frantic", "fratchy", "fraught", "freaky", "freckly", "free", "freebie", "freed", "freeing",
  "freer", "freest", "fremd", "french", "frenchy", "fresh", "fretful", "fretted", "fretty", "friable", "fribble",
  "fried", "frigid", "frilled", "frilly", "fringe", "fringed", "fringy", "frisky", "frizzly", "frizzy", "frogged",
  "froggy", "frolic", "fronded", "front", "frontal", "frore", "frosted", "frosty", "frothy", "froward", "frowsty",
  "frowsy", "frowzy", "frozen", "fructed", "frugal", "fruited", "fruity", "frumpy", "fubsier", "fubsy", "fucoid",
  "fuddled", "fugal", "fugato", "fuggy", "fulani", "fulgent", "fulgid", "full", "fulsome", "fulvous", "fumed",
  "fumier", "fumiest", "fumy", "fun", "funded", "funest", "fungal", "fungoid", "fungous", "funked", "funkier",
  "funky", "funnier", "funny", "furcate", "furioso", "furious", "furled", "furred", "furrowy", "furry", "further",
  "furtive", "furzy", "fuscous", "fused", "fusible", "fusil", "fusile", "fussier", "fussy", "fustian", "fustier",
  "fusty", "futile", "future", "fuzzed", "fuzzier", "fuzzy", "gabby", "gabled", "gadoid", "gaga", "gala", "galeate",
  "galenic", "gallant", "galled", "gallic", "galling", "galore", "gambia", "gambrel", "game", "gamer", "gamest",
  "gametic", "gamey", "gamic", "gamier", "gamiest", "gammy", "gamy", "gangly", "ganoid", "gaping", "garbed",
  "garbled", "gardant", "gargety", "garish", "garni", "gaseous", "gashed", "gasping", "gastric", "gated", "gauche",
  "gaudy", "gauge", "gaulish", "gaunt", "gauzy", "gawkier", "gawky", "gawsy", "gay", "geared", "geegaw", "gelded",
  "gelid", "gemel", "gemmate", "gemmed", "gemmier", "gemmy", "genal", "general", "generic", "genetic", "genevan",
  "genoese", "genteel", "gentile", "gentle", "gentled", "gentler", "genty", "genuine", "geodic", "geoidal", "georgic",
  "german", "germane", "gestic", "gewgaw", "ghast", "ghastly", "ghostly", "giant", "gibbed", "gibbose", "gibbous",
  "giddied", "giddier", "giddy", "gifted", "giggly", "gilded", "gilled", "gilt", "gimlet", "gimpy", "ginger",
  "gingery", "ginned", "giocoso", "girlish", "girly", "girt", "given", "giving", "glacial", "glad", "glaikit",
  "glairy", "glaived", "glare", "glarier", "glaring", "glary", "glazed", "gleeful", "gleety", "gleg", "glenoid",
  "glial", "glib", "glibber", "global", "globate", "globoid", "globose", "gloomy", "glossy", "glottal", "glottic",
  "gloved", "glowing", "glued", "gluey", "glum", "glummer", "glumpy", "gluteal", "glutted", "glyphic", "glyptic",
  "gnarled", "gnarly", "gnathic", "gnomic", "gnomish", "gnostic", "goaded", "goateed", "goatish", "godless",
  "godlier", "godly", "going", "gold", "golden", "gone", "gonidic", "good", "goodish", "goodly", "gooey", "goofier",
  "goofy", "gooier", "gooiest", "goosey", "goosy", "gordian", "gorged", "gorier", "goriest", "gorsy", "gory",
  "gossipy", "gothic", "goutier", "gouty", "gowaned", "gowany", "gowned", "grab", "gracile", "grade", "graded",
  "gradely", "gradual", "grained", "grainy", "grand", "granted", "graphic", "grapier", "grapy", "grating", "gratis",
  "grave", "gravel", "graven", "gravest", "gravid", "gray", "grayish", "grazed", "greased", "greasy", "great",
  "greater", "greaved", "grecian", "greedy", "greek", "green", "greige", "grey", "greyish", "grilled", "grim",
  "grimier", "grimmer", "grimy", "gripple", "grippy", "grisly", "gristly", "gritty", "grizzly", "groggy", "grolier",
  "groomed", "grooved", "groovy", "groping", "gross", "grotian", "grotty", "grouchy", "ground", "group", "grouped",
  "grouse", "grouty", "growing", "grown", "grubby", "gruff", "grum", "grumbly", "grummer", "grumose", "grumous",
  "grumpy", "grungy", "guam", "guarded", "gude", "guelfic", "guest", "guided", "guiding", "guilty", "guinean",
  "gular", "gules", "gulfy", "gummed", "gummier", "gummous", "gummy", "gunless", "gunned", "guns", "gushier",
  "gushing", "gushy", "gustier", "gusty", "gutless", "gutsier", "gutsy", "gutta", "guttate", "gyral", "gyrate",
  "gyronny", "gyrose", "habile", "habited", "hack", "hacking", "hackly", "hadal", "haemal", "haemic", "haggard",
  "haggish", "haired", "hairier", "hairy", "haitian", "halcyon", "hale", "halest", "half", "halfway", "haloid",
  "halt", "halted", "halting", "hamate", "hamitic", "hammier", "hammy", "hamular", "handed", "handier", "handled",
  "handy", "hangdog", "hanging", "hapless", "haploid", "happier", "happy", "haptic", "hard", "hardier", "hardy",
  "harlot", "harmed", "harmful", "harried", "harsh", "hasidic", "hask", "hastate", "hastier", "hasty", "hatable",
  "hatched", "hated", "hateful", "hatless", "hatted", "haughty", "haunted", "hawkish", "haywire", "hazel", "hazelly",
  "hazier", "haziest", "hazy", "head", "headed", "headier", "heady", "healed", "healing", "healthy", "heaped",
  "heaping", "heapy", "heard", "hearing", "hearsay", "hearted", "hearty", "heated", "heathen", "heather", "heathy",
  "heating", "heavier", "heavies", "heaving", "heavy", "hebraic", "hebrew", "hectic", "hedged", "hedgier", "hedgy",
  "hedonic", "heedful", "heeled", "heftier", "hefty", "heigh", "heinous", "held", "heliac", "helical", "helmed",
  "helpful", "hemal", "hempen", "hempy", "hennaed", "hep", "hepatic", "herbal", "herbier", "herby", "herding", "here",
  "hernial", "het", "hewn", "hex", "hexadic", "hexed", "hick", "hidden", "hideous", "hiemal", "high", "higher",
  "highest", "hilar", "hilding", "hillier", "hilly", "hind", "hinder", "hindu", "hip", "hipped", "hipper", "hippest",
  "hippier", "hippy", "hirable", "hircine", "hired", "hirsute", "hispid", "hissing", "histie", "histoid", "hit",
  "hitchy", "hither", "hobbes", "hobnail", "hoc", "hogged", "hoggish", "hoiden", "hokey", "holding", "holey",
  "holier", "holies", "holiest", "hollow", "holmic", "holy", "home", "homely", "homeric", "homier", "homiest",
  "homing", "hominid", "homy", "honest", "honey", "honied", "honour", "hooded", "hoofed", "hooked", "hookier",
  "hooly", "hopeful", "hopping", "horal", "horary", "horned", "hornier", "hornish", "horrent", "horrid", "horsey",
  "horsier", "horsy", "hostile", "hot", "hotfoot", "hotshot", "hotter", "hottest", "hotting", "hottish", "hourly",
  "hoven", "howe", "howling", "hoyden", "huddled", "hued", "hueless", "huffier", "huffing", "huffish", "huffy",
  "huge", "huger", "hugest", "hulkier", "hulking", "hulky", "human", "humane", "humble", "humbled", "humbler",
  "humdrum", "humeral", "humic", "humid", "hummel", "humming", "humoral", "humpier", "humpy", "hunched", "hundred",
  "hung", "hungry", "hunky", "hunnish", "hunted", "hurling", "hurried", "hurt", "hurtful", "hushed", "huskier",
  "husky", "hussite", "hyaline", "hyaloid", "hybrid", "hydric", "hydro", "hydroid", "hydrous", "hydroxy", "hyetal",
  "hygeian", "hymnal", "hyoid", "hyphal", "hypnoid", "hypoxic", "iambic", "iatric", "iberian", "icarian", "iced",
  "icier", "iciest", "ickier", "ickiest", "icky", "iconic", "icteric", "ictic", "icy", "idaean", "idahoan", "ideal",
  "idem", "identic", "idiotic", "idle", "idled", "idlest", "idling", "idyllic", "iffy", "igneous", "ignited",
  "ignored", "iguana", "iguanid", "ileac", "iliac", "ilka", "ill", "illicit", "imagism", "imagist", "imbued",
  "imidic", "immane", "immense", "immoral", "immune", "impavid", "impeded", "impel", "impious", "implied", "imposed",
  "impure", "inane", "inapt", "inboard", "inborn", "inbound", "inbreed", "inby", "incan", "incased", "incised",
  "incivil", "incog", "incrust", "incult", "incuse", "indian", "indic", "indign", "indoor", "indrawn", "induced",
  "inept", "inert", "inexact", "infant", "infect", "infelt", "infidel", "infirm", "inform", "ingoing", "ingrain",
  "ingrate", "ingrown", "inhaled", "inhuman", "inhumed", "initial", "injured", "inkier", "inkiest", "inky", "inlaid",
  "inland", "inlying", "inmost", "innate", "inner", "inphase", "inrush", "insane", "inside", "insides", "insipid",
  "instant", "insular", "insured", "intact", "intense", "intent", "inter", "interim", "intern", "intime", "intoed",
  "intoned", "intown", "inured", "invalid", "inverse", "invited", "inward", "iodic", "iodized", "iodous", "ionian",
  "ionic", "ionized", "iracund", "iranian", "iraqi", "irate", "ireful", "irenic", "iridic", "irish", "iritic",
  "irksome", "iron", "ironed", "ironic", "irony", "ish", "isiac", "islamic", "isogamy", "isolate", "isopod",
  "israeli", "issuant", "italian", "italic", "itchier", "itching", "itchy", "iterant", "ithaca", "ivied", "jack",
  "jacobin", "jade", "jaded", "jadish", "jagged", "jaggier", "jaggy", "jailed", "jain", "jainism", "jake", "jalapic",
  "jamaica", "jammed", "jammy", "jangly", "jannock", "jarring", "jasp", "jaspery", "jaunty", "java", "jealous",
  "jeering", "jejune", "jelled", "jellied", "jessant", "jesting", "jet", "jetting", "jetty", "jeweled", "jewish",
  "jilted", "jimp", "jingly", "jinxed", "jittery", "jobless", "jocose", "jocular", "jocund", "joined", "joint",
  "jointed", "joking", "jollier", "jolly", "jolted", "joltier", "jolting", "jolty", "jovial", "jovian", "jowled",
  "jowlier", "jowly", "joyce", "joycean", "joyful", "joyless", "joyous", "jubate", "judaean", "judaic", "judean",
  "jugal", "jugate", "jugular", "juicier", "juicy", "julian", "jumbled", "jumbo", "jumpier", "jumping", "jumpy",
  "jungian", "jungly", "junior", "junked", "jural", "jurant", "juridic", "jury", "jussive", "just", "jutting",
  "juvenal", "kacha", "kafka", "kantian", "kaput", "karaite", "karmic", "karoo", "karstic", "kayoed", "keeled",
  "keen", "keltic", "kempt", "kenotic", "kentish", "kenyan", "kept", "keramic", "key", "keyless", "khaki", "khmer",
  "killing", "kilted", "kin", "kind", "kindled", "kindly", "kindred", "kinetic", "kingly", "kinless", "kirtled",
  "kitsch", "kittle", "klutzy", "knaggy", "knarred", "knavish", "knitted", "knotted", "knotty", "knowing", "known",
  "knuckly", "knurled", "knurly", "kookie", "kookier", "kooky", "koranic", "korean", "kosher", "kraal", "kufic",
  "kurdish", "kutcha", "kuwaiti", "labile", "labored", "labrid", "labroid", "laced", "lacier", "laciest", "lacking",
  "laconia", "laconic", "lacteal", "lactic", "lacunal", "lacunar", "lacy", "laddery", "laddish", "laden", "ladyish",
  "laggard", "laic", "laid", "laigh", "lairy", "laith", "lakier", "lakiest", "laky", "lamaism", "lambent", "lame",
  "lamer", "lamest", "laminar", "laming", "lamplit", "lanate", "land", "landed", "lane", "lang", "langued", "languid",
  "laniary", "lank", "lanky", "lanose", "lao", "laos", "laotian", "lapp", "lapsed", "lardier", "lardy", "large",
  "larger", "largest", "largish", "largo", "larine", "larkish", "larky", "larval", "lashed", "lashing", "last",
  "lasting", "latched", "late", "lated", "lateen", "latent", "later", "lateral", "latest", "lathery", "lathier",
  "lathy", "latin", "latino", "latish", "latter", "latvian", "lavish", "lawful", "lawless", "lawny", "lax", "lay",
  "layered", "lazier", "laziest", "lazy", "leachy", "leaded", "leaden", "leadier", "leading", "leady", "leafed",
  "leafier", "leafy", "leaking", "leaky", "leal", "lean", "leaning", "leaping", "learned", "leary", "leased", "least",
  "leaved", "led", "ledgier", "ledgy", "lee", "leerier", "leering", "leery", "leeward", "left", "leftish", "leftist",
  "legal", "legato", "legged", "leggier", "leggy", "legible", "legion", "legit", "legless", "leisure", "lemnian",
  "lemony", "lengthy", "lenient", "lenis", "lenten", "lentic", "lento", "lentoid", "leonine", "leprose", "leprous",
  "lesbian", "less", "lesser", "lethal", "lettic", "lettish", "level", "lewd", "lexical", "liable", "lianoid",
  "liberal", "libyan", "licht", "licit", "licked", "lidded", "lidless", "lief", "liege", "lienal", "lifeful",
  "lifted", "light", "lighted", "lignite", "ligular", "likable", "lilac", "lilied", "lilting", "limbate", "limbed",
  "limber", "limbic", "lime", "limier", "limiest", "liminal", "limited", "limp", "limpid", "lineal", "linear",
  "lineate", "lined", "liney", "lingual", "linked", "linnean", "lintier", "linty", "liny", "lionly", "lipless",
  "lipoid", "lipped", "lippy", "liquid", "lissom", "lissome", "listed", "lit", "lite", "literal", "lithe", "lither",
  "lithest", "lithic", "litho", "lithoid", "litten", "littery", "little", "littler", "livable", "live", "lived",
  "lively", "livery", "livid", "living", "loaded", "loading", "loamy", "loath", "loathly", "lobar", "lobate", "lobed",
  "lobose", "lobular", "local", "located", "lochial", "locked", "loco", "locrian", "locular", "lodged", "loftier",
  "lofty", "log", "logical", "logy", "lolling", "londony", "lone", "lonely", "long", "longer", "longest", "longing",
  "longish", "looking", "loonier", "loonies", "loony", "looped", "loopy", "loose", "looser", "loosest", "looted",
  "lopped", "loral", "lordly", "lorn", "losable", "losel", "losing", "lossy", "lost", "loth", "lotic", "louche",
  "loud", "loudish", "louring", "loury", "lousier", "lousy", "loutish", "louvred", "lovable", "loved", "lovely",
  "loverly", "loving", "low", "lower", "lowered", "lowery", "lowest", "lowland", "lowlier", "lowly", "lown", "lowse",
  "loyal", "lozengy", "lubric", "lucan", "lucent", "lucid", "luckier", "lucky", "luddite", "luetic", "lulling",
  "lumbar", "lumpen", "lumpier", "lumpy", "lunar", "lunate", "lunatic", "lunular", "lupine", "lurdan", "lurid",
  "lurking", "lush", "lushy", "luteal", "luteous", "luxe", "luxury", "lydian", "lying", "lyncean", "lyrate", "lyric",
  "lyrical", "macabre", "macadam", "macho", "macled", "macro", "macular", "mad", "madcap", "maddest", "madding",
  "made", "magenta", "maggoty", "magian", "magic", "magical", "magyar", "mahdi", "maiden", "maigre", "mailed",
  "maimed", "main", "mair", "major", "makable", "malar", "malay", "male", "malefic", "malign", "maltese", "malty",
  "mammary", "mammoth", "man", "manchu", "manchus", "mande", "maned", "manful", "mangier", "mangled", "mangy",
  "maniac", "manic", "manky", "manlier", "manly", "manned", "mannish", "mansard", "mantic", "mantled", "mantuan",
  "manual", "manx", "many", "maoism", "maori", "marathi", "marble", "marbled", "marcan", "mardy", "marian", "marine",
  "marish", "marital", "marked", "marled", "marly", "maroon", "marred", "married", "marshy", "martial", "martian",
  "marxian", "marxist", "masked", "masking", "masonic", "masted", "master", "mastoid", "mat", "matched", "mated",
  "matey", "matin", "matt", "matte", "matted", "mattery", "mature", "matured", "maudlin", "maungy", "mauve",
  "mawkish", "maxi", "maximal", "maximum", "mayan", "mayoral", "mazed", "mazier", "maziest", "mazy", "meager",
  "meagre", "mealier", "mealy", "mean", "meaning", "measled", "measly", "meatal", "meatier", "meaty", "medal", "mede",
  "medial", "median", "mediate", "medical", "medium", "medley", "meek", "meet", "meiotic", "melanic", "melic",
  "mellow", "melodic", "melted", "melting", "menial", "mensal", "mental", "mercian", "mere", "merest", "merged",
  "merging", "merino", "merited", "merrier", "merry", "mesarch", "meshed", "meshuga", "mesial", "mesic", "mesne",
  "mesonic", "messier", "messy", "metal", "metopic", "metric", "mettled", "mexican", "miasmal", "miasmic", "micro",
  "mid", "middle", "midget", "midi", "midian", "midland", "midmost", "midship", "midway", "miffed", "miffier",
  "miffy", "mighty", "mignon", "migrant", "milch", "mild", "mildewy", "miliary", "milk", "milkier", "milky", "milled",
  "milling", "million", "millrun", "mim", "mimetic", "mimic", "mimical", "mincing", "minded", "mindful", "mined",
  "mineral", "mingy", "mini", "minikin", "minim", "minimal", "minimum", "minimus", "minion", "minoan", "minor",
  "mint", "minus", "minute", "miocene", "miotic", "mired", "mirier", "miriest", "mirkier", "mirky", "miry", "mis",
  "miserly", "mishnic", "mislaid", "missed", "missing", "missive", "mistier", "misty", "misused", "mitered",
  "mitotic", "mitral", "mixable", "mixed", "mizzen", "mnemic", "moanful", "moaning", "moated", "mob", "mobbish",
  "mobile", "mock", "mocking", "mod", "modal", "model", "modeled", "modern", "modest", "modish", "modular", "moire",
  "moist", "molal", "molar", "molded", "moldy", "moline", "molten", "monacid", "monaco", "monarch", "mondial",
  "monied", "monism", "monkish", "mono", "monodic", "montane", "monthly", "mony", "moodier", "moody", "mooned",
  "moonish", "moonlit", "moony", "moorish", "moory", "moot", "mopey", "mopier", "mopiest", "mopy", "moral", "morbid",
  "mordant", "more", "moreish", "moresco", "morisco", "morish", "mornay", "morning", "morose", "mortal", "mosaic",
  "mossier", "mossy", "most", "motey", "mothier", "mothy", "motile", "motive", "motley", "motor", "motored",
  "mottled", "mouldy", "mounted", "mousey", "mousier", "mousy", "mouthy", "movable", "moved", "moving", "mown",
  "mozart", "much", "mucic", "mucid", "muckier", "mucking", "muckle", "mucky", "mucoid", "mucous", "muddied",
  "muddier", "muddled", "muddy", "muggier", "muggy", "muley", "mulish", "mulley", "mum", "mundane", "mural", "murine",
  "murk", "murky", "murrey", "muscid", "muscly", "museful", "mushier", "mushy", "musical", "musing", "muskier",
  "musky", "muslim", "mussier", "mussy", "must", "mustier", "musty", "mutable", "mutant", "mute", "muted", "muttony",
  "mutual", "muzzy", "myalgic", "myeloid", "myoid", "myopic", "myotic", "myriad", "mystic", "mythic", "mzee",
  "nacred", "nae", "naevoid", "nagging", "naggy", "naiant", "naif", "naive", "named", "naming", "napless", "napped",
  "nappier", "napping", "narial", "narrow", "nary", "nasal", "nascent", "nasmyth", "nastier", "natal", "natant",
  "native", "nattier", "natty", "natural", "naught", "naughty", "naval", "neap", "neaped", "near", "nearer",
  "nearest", "neat", "nebular", "nebule", "nebuly", "needed", "needful", "needier", "needy", "nematic", "neogene",
  "neozoic", "nepali", "nephric", "nepotic", "neritic", "nerval", "nervate", "nervine", "nervous", "nervy", "nesh",
  "nested", "nestled", "net", "nether", "nett", "netted", "nettled", "nettly", "neural", "neuron", "neuter",
  "neutral", "new", "newborn", "newest", "newish", "newsier", "newsy", "next", "nibbed", "nicaean", "nice", "nicene",
  "nicer", "nicest", "nickel", "niffy", "niftier", "nifty", "nilotic", "nimble", "nine", "ninety", "ninth", "niobean",
  "niobic", "niobous", "nisi", "nitid", "nitric", "nitrous", "nittier", "nitty", "nival", "niveous", "nocent",
  "noctuid", "nocuous", "nodal", "nodding", "nodical", "nodose", "nodous", "nodular", "noduled", "noetic", "noisier",
  "noisome", "noisy", "nomadic", "nominal", "non", "nonaged", "nonagon", "nonary", "nonuple", "nordic", "normal",
  "norman", "norse", "north", "nosed", "nosey", "nosier", "nosiest", "nosy", "notable", "notal", "notched", "notchy",
  "noted", "noticed", "notour", "novel", "novice", "nowed", "noxious", "nth", "nubbly", "nubby", "nubian", "nubile",
  "nuclear", "nude", "nudist", "nuggety", "null", "numb", "numbing", "numeral", "numeric", "numidia", "nummary",
  "nuptial", "nursed", "nutant", "nuts", "nutty", "oafish", "oak", "oaken", "oared", "oarless", "oaten", "obconic",
  "obese", "oblate", "obliged", "oblique", "oblong", "obovate", "obovoid", "obscene", "obscure", "obtect", "obtuse",
  "obverse", "obvious", "occult", "oceanic", "ocellar", "oceloid", "ocher", "ochery", "ochre", "ocker", "ocreate",
  "octadic", "octal", "octaval", "octave", "octopod", "octuple", "ocular", "odd", "oddball", "odious", "odorous",
  "off", "offbeat", "offhand", "offish", "offside", "often", "ogreish", "ogygian", "ohmic", "oiled", "oilier",
  "oiliest", "oily", "okay", "oke", "old", "olden", "older", "oldest", "oldish", "oleic", "olid", "olivary", "olive",
  "olympic", "omental", "ominous", "omnibus", "omnific", "once", "one", "oneiric", "ongoing", "oniony", "only",
  "onside", "onstage", "onward", "onymous", "oolitic", "oozier", "ooziest", "oozing", "oozy", "opaline", "opaque",
  "ope", "open", "opened", "opening", "operant", "ophitic", "opiate", "oppidan", "opposed", "opsonic", "optic",
  "optical", "optimal", "optimum", "oral", "orange", "orbital", "ordered", "orderly", "ordinal", "orectic", "orient",
  "ornate", "ornery", "orotund", "orphan", "orphean", "orphic", "ortho", "oscan", "oscine", "oscular", "osiered",
  "osmanli", "osmic", "osmious", "osmotic", "osmous", "osseous", "ossie", "osteal", "osteoid", "other", "otic",
  "otiose", "ottoman", "out", "outback", "outbred", "outcast", "outdone", "outdoor", "outer", "outland", "outlaw",
  "outmost", "outside", "outsize", "outward", "outworn", "oval", "ovarian", "ovate", "over", "overall", "overarm",
  "overdue", "overfar", "overfed", "overrun", "oversea", "overt", "ovidian", "oviform", "ovine", "ovoid", "ovular",
  "owed", "owing", "owlish", "own", "owned", "oxalic", "oxblood", "oxonian", "paced", "pacific", "packed", "padded",
  "paduan", "pagan", "paginal", "paid", "pained", "painful", "painted", "paired", "palatal", "pale", "paled", "paler",
  "palest", "paling", "palish", "pallial", "pallid", "pally", "palmar", "palmary", "palmate", "palmier", "palmy",
  "palpate", "palsied", "paltry", "paludal", "paly", "pampean", "pan", "pandean", "paned", "paneled", "panicky",
  "panjabi", "panzer", "papal", "paper", "papery", "paphian", "pappose", "pappy", "papuan", "par", "parched",
  "pardine", "paretic", "parian", "paris", "parked", "parky", "parlous", "parnell", "parodic", "parol", "parotic",
  "parotid", "part", "parted", "parthia", "partial", "parting", "party", "parvenu", "paschal", "pashto", "past",
  "pasted", "pastel", "pat", "patched", "patchy", "patent", "pathic", "patient", "pauline", "paunchy", "pausal",
  "paved", "pavid", "pawky", "payable", "paying", "peachy", "peak", "peaked", "peaky", "peanut", "pearl", "pearly",
  "peart", "peatier", "peaty", "pebbly", "peccant", "peckish", "pectic", "pedal", "pedate", "peeled", "peeling",
  "peeved", "peevish", "peewee", "pelagic", "pelitic", "peloric", "peltate", "pelting", "pelvic", "penal", "pendant",
  "pendent", "pending", "pennate", "penned", "pennied", "penny", "pensile", "pensive", "pent", "peopled", "peppery",
  "peppier", "peppy", "peptic", "percent", "perched", "percoid", "perdu", "perfect", "perfumy", "perk", "perked",
  "perkier", "perky", "permed", "permian", "persian", "persons", "pert", "peruked", "peskier", "pesky", "pet",
  "petrine", "petrous", "pettier", "pettish", "petty", "pewter", "phantom", "phasic", "phasmid", "phatic", "phlegmy",
  "phobic", "phocine", "phonal", "phoney", "phonic", "phonier", "phonies", "phony", "photic", "phrasal", "phrenic",
  "physic", "piano", "piceous", "picked", "pickier", "pickled", "picky", "picric", "piebald", "pied", "pierced",
  "pierian", "piggie", "piggish", "piggy", "pileate", "piled", "pileous", "pillowy", "pilose", "pilot", "pilous",
  "pinched", "pineal", "piney", "pinguid", "pinier", "piniest", "pink", "pinkish", "pinnate", "pinned", "pinto",
  "piny", "pious", "pipier", "pipiest", "piping", "pipy", "piquant", "pique", "piratic", "pitched", "pitchy",
  "piteous", "pithy", "pitiful", "pitted", "pitying", "pivotal", "placed", "placid", "placoid", "plagal", "plagued",
  "plaguey", "plaguy", "plaided", "plain", "planar", "plane", "planned", "plantar", "planted", "plashy", "plastic",
  "plated", "platier", "platy", "play", "playful", "playing", "pleased", "pleated", "plebby", "pledged", "plenary",
  "pleural", "pliable", "pliant", "plical", "plicate", "plosive", "plotful", "plotted", "plucked", "plucky", "plum",
  "plumate", "plumb", "plumbed", "plumbic", "plumed", "plumier", "plummy", "plumose", "plump", "plumy", "plural",
  "plus", "plush", "plusher", "plushy", "pluteal", "pluvial", "poached", "poachy", "pocked", "pockier", "pocky",
  "poco", "podgier", "podgy", "poetic", "pointed", "poised", "pokey", "pokier", "pokies", "pokiest", "poky", "polar",
  "polemic", "polish", "polite", "politic", "polled", "polypod", "pomaded", "pompous", "ponceau", "pongid", "poor",
  "poorest", "poorly", "pop", "poppied", "pops", "porcine", "porkier", "porky", "porose", "porous", "porrect", "port",
  "portly", "posh", "post", "postal", "postern", "potable", "potamic", "potent", "potted", "pottier", "potty",
  "pouched", "pouring", "powdery", "power", "powered", "practic", "pre", "preachy", "preborn", "precast", "precise",
  "predial", "prefab", "premed", "premier", "premium", "preoral", "prepaid", "present", "preset", "pressed",
  "pressor", "prest", "presto", "pretend", "pretty", "prewar", "priapic", "prim", "prima", "primal", "primary",
  "primate", "prime", "primed", "primsie", "print", "printed", "prior", "prissy", "private", "privies", "privy",
  "prize", "pro", "probing", "profane", "profuse", "prolate", "prolix", "prompt", "proof", "proofed", "proper",
  "prosaic", "prosy", "protean", "proto", "proud", "proved", "proven", "proximo", "proxy", "prudent", "prudish",
  "pruned", "prunted", "prying", "pseud", "pseudo", "psychic", "psycho", "public", "pucka", "puckery", "puckish",
  "puerile", "puff", "puffed", "puffier", "puffing", "puffy", "puggish", "puggy", "puir", "puisne", "pukka", "puling",
  "pulled", "pulpier", "pulpy", "pulsed", "pulsing", "punchy", "pungent", "punic", "punier", "puniest", "punjabi",
  "punk", "punkah", "puny", "pupal", "puranic", "pure", "purer", "purest", "purging", "puritan", "purple", "purpure",
  "pursier", "pursued", "pursy", "pushed", "pushful", "pushier", "pushing", "pushto", "pushy", "putrid", "puzzled",
  "pyaemic", "pygmoid", "pyknic", "pyloric", "pyoid", "pyralid", "pyretic", "pyritic", "pyrrhic", "pyrrho", "pythian",
  "quack", "quadric", "quaggy", "quaint", "quaker", "quakier", "quaking", "quaky", "quality", "quantal", "quare",
  "quartan", "quarter", "quartic", "quasi", "quavery", "queasy", "queenly", "queer", "quelled", "quick", "quiet",
  "quilted", "quinary", "quinate", "quinoid", "quintan", "quintic", "quirky", "quit", "quits", "quivery", "quondam",
  "rabic", "rabid", "racemed", "racemic", "racial", "racier", "raciest", "racing", "racist", "rackety", "racking",
  "racy", "raddled", "radial", "radiant", "radiate", "radical", "radio", "radular", "raffish", "ragged", "raggedy",
  "raging", "raglan", "raiding", "rainier", "raining", "rainy", "raised", "raising", "raked", "rakish", "ralline",
  "ramal", "rammish", "ramose", "rampant", "ramstam", "rancid", "randie", "random", "randy", "ranged", "rangier",
  "ranging", "rangy", "rank", "ranked", "rankine", "ranking", "rapid", "raploch", "rapt", "rare", "rarer", "rarest",
  "raring", "rascal", "rash", "raspier", "rasping", "raspy", "ratable", "rath", "rathe", "rattier", "rattish",
  "rattled", "rattly", "ratty", "raucous", "raunchy", "raving", "raw", "rawish", "rayless", "razed", "read",
  "readier", "ready", "real", "rear", "rearing", "rebel", "reboant", "reborn", "rebuilt", "rebuked", "recent",
  "recluse", "record", "red", "redder", "reddest", "reddish", "reduced", "reedier", "reedy", "reeking", "reeky",
  "refer", "refined", "reflex", "regal", "regent", "regnal", "regnant", "regular", "related", "relaxed", "relaxer",
  "reliant", "remiss", "remnant", "remote", "remoter", "removed", "renal", "rending", "renewed", "rent", "rental",
  "repand", "repent", "replete", "reptant", "reptile", "reputed", "rescued", "reserve", "rested", "resting",
  "restive", "retail", "retial", "retiary", "retinal", "retired", "retral", "retuse", "revered", "reverse", "review",
  "reviled", "revised", "revived", "rhaetic", "rhemish", "rhenish", "rheumy", "rhinal", "rhodian", "rhodic",
  "rhombic", "rhotic", "rhymed", "rhyming", "riant", "ribald", "ribbed", "ribbony", "ribless", "rich", "rickety",
  "rid", "ridable", "ridden", "riddled", "rident", "ridged", "ridgier", "ridgy", "riding", "rife", "rifled", "rigged",
  "right", "rights", "rigid", "riled", "rimed", "riming", "rimless", "rimmed", "rimose", "rimy", "rindy", "ringed",
  "ringent", "ringing", "riotous", "ripe", "ripened", "ripped", "ripping", "ripple", "rippled", "ripply", "risen",
  "risible", "rising", "riskier", "risky", "ritual", "ritzier", "ritzy", "rival", "riven", "road", "roan", "roaring",
  "roast", "roasted", "robed", "robust", "rockier", "rocky", "rococo", "rodded", "rodless", "roguish", "roiled",
  "roilier", "roiling", "roily", "rolled", "rolling", "romaic", "roman", "romance", "romanic", "romansh", "romish",
  "rommany", "roofed", "rooky", "roomier", "roomy", "root", "rooted", "ropable", "ropey", "ropier", "ropiest", "ropy",
  "roscian", "rose", "roseate", "rosiny", "rostral", "rosy", "rotary", "rotate", "rotated", "rotted", "rotten",
  "rotting", "rotund", "rouged", "rough", "round", "rounded", "roupy", "rousing", "routed", "routine", "roving",
  "rowdy", "royal", "rubber", "rubbery", "rubbly", "rubied", "rubify", "rubious", "rubric", "ruby", "ruddier",
  "ruddy", "rude", "ruderal", "rudish", "rueful", "ruffed", "ruffled", "rufous", "rugged", "rugose", "ruined",
  "ruinous", "ruled", "ruling", "ruly", "rum", "rumbly", "rummy", "rumpled", "runaway", "runed", "runic", "runnier",
  "running", "runny", "runtier", "runtish", "runty", "rural", "rush", "rushed", "rushier", "rushing", "rushy", "russ",
  "russet", "russety", "russian", "russky", "rust", "rusted", "rustic", "rustier", "rustred", "rusty", "ruthful",
  "rutted", "ruttier", "ruttish", "rutty", "sabaean", "sabean", "sabine", "sable", "sad", "saddled", "safe", "sage",
  "sagging", "saharan", "said", "sailing", "sainted", "saintly", "saiva", "salable", "sales", "salian", "salic",
  "salient", "saline", "salique", "sallow", "sallowy", "salt", "saltant", "saltato", "salted", "saltier", "saltish",
  "salty", "salving", "same", "samian", "samnite", "samoa", "samoan", "sanded", "sandier", "sandy", "sane", "saner",
  "sanest", "sanious", "sap", "sapid", "sapient", "sapless", "sapphic", "sappier", "sappy", "saracen", "sarcoid",
  "sarcous", "sarky", "saronic", "satanic", "sated", "satem", "satiate", "satin", "satiny", "satiric", "satyric",
  "saucier", "saucy", "saurian", "saut", "savable", "saved", "saving", "savory", "savoury", "savvy", "saxon",
  "saxonic", "sayable", "scabby", "scalar", "scald", "scaldic", "scaled", "scalene", "scalier", "scalled", "scaly",
  "scant", "scanty", "scarce", "scarcer", "scared", "scarey", "scarlet", "scarred", "scary", "scenic", "scented",
  "sceptic", "schlock", "sciatic", "scopate", "score", "scorned", "scotch", "scotism", "scots", "scoured", "scraggy",
  "scratch", "scrawly", "scrawny", "screaky", "screwy", "scribal", "scrimp", "scrimpy", "scrotal", "scrub", "scrubby",
  "scruffy", "scungy", "scurfy", "scurry", "scurvy", "scutate", "sea", "sealed", "seamed", "seamier", "seamy", "sear",
  "seared", "seasick", "seaside", "seated", "seaward", "sebacic", "sec", "second", "secret", "sectile", "secular",
  "secund", "secure", "secured", "sedate", "sedated", "sedged", "sedgy", "seeable", "seeded", "seedier", "seedy",
  "seeing", "seeking", "seely", "seeming", "seemly", "seen", "seeping", "seismal", "seismic", "seized", "sejant",
  "select", "selenic", "self", "selfish", "seljuk", "sematic", "semi", "seminal", "semitic", "senary", "senecan",
  "senile", "senior", "sensate", "sensed", "sensory", "sensual", "sent", "sepia", "septal", "septate", "septic",
  "sequent", "seral", "serb", "serbian", "sere", "serene", "serfish", "serial", "seriate", "serious", "serrate",
  "serried", "servian", "servile", "servo", "sessile", "set", "setose", "setting", "settled", "seven", "seventh",
  "seventy", "several", "severe", "severed", "severer", "sewed", "sewn", "shabby", "shaded", "shadowy", "shady",
  "shaken", "shakier", "shaking", "shaky", "shallow", "shalwar", "sham", "shamed", "shang", "shaped", "shapely",
  "shaping", "shared", "sharing", "sharp", "sheared", "sheathy", "shed", "sheen", "sheer", "shelfy", "shelvy",
  "shiah", "shier", "shiest", "shifty", "shiite", "shill", "shingly", "shinier", "shining", "shinto", "shiny",
  "shirty", "shivery", "shoal", "shoaly", "shock", "shocked", "shod", "shoddy", "shorn", "short", "shorty", "shot",
  "shotgun", "shotten", "shouted", "showery", "showier", "showy", "shrewd", "shrill", "shrimpy", "shrubby", "shrunk",
  "shut", "shy", "shyer", "shyest", "sialoid", "siamese", "siberia", "sibylic", "sic", "sick", "sicker", "sickish",
  "sickly", "side", "sidearm", "sienese", "sighful", "sighted", "sightly", "sigmate", "sigmoid", "sign", "signal",
  "signed", "sikh", "silent", "silicic", "silken", "silkier", "silky", "silly", "siltier", "silty", "silurid",
  "silvan", "silver", "silvern", "silvery", "simian", "similar", "simious", "simular", "sincere", "sinewy", "sinful",
  "singing", "single", "singled", "sinless", "sinning", "sinuate", "sinuous", "sirenic", "sister", "sistine",
  "sitting", "situate", "situla", "siwash", "six", "sixfold", "sixteen", "sixth", "sixty", "sizable", "size", "sized",
  "sizy", "skaldic", "skeigh", "skeptic", "sketchy", "skew", "skewed", "ski", "skiable", "skilful", "skilled", "skim",
  "skimmed", "skimpy", "skin", "skinned", "skinny", "skint", "skyward", "slack", "slain", "slaked", "slangy", "slant",
  "slanted", "slapped", "slashed", "slate", "slatier", "slaty", "slave", "slavic", "slavish", "sleazy", "sleek",
  "sleekit", "sleeky", "sleepy", "sleety", "sleeved", "slender", "sliced", "slick", "slicked", "sliding", "slier",
  "sliest", "slight", "slim", "slimed", "slimier", "slimmer", "slimsy", "slinky", "slippy", "slit", "sloped",
  "sloping", "slopped", "sloppy", "sloshed", "sloshy", "slouchy", "sloughy", "slovak", "slovene", "slow", "slub",
  "slubbed", "sludgy", "slum", "slummy", "slumped", "slung", "slurred", "slushy", "sly", "small", "smaller", "smarmy",
  "smart", "smarty", "smashed", "smeared", "smeary", "smectic", "smelly", "smiling", "smitten", "smoggy", "smoked",
  "smokier", "smoking", "smooth", "smudged", "smudgy", "smug", "smugger", "snafu", "snaggy", "snakier", "snaky",
  "snarled", "snarly", "snatchy", "sneak", "sneaky", "sneezy", "snide", "snider", "snidest", "sniffy", "snod",
  "snoopy", "snooty", "snoozy", "snoring", "snorty", "snotty", "snouted", "snowier", "snowy", "snub", "snubby",
  "snug", "snugger", "soaked", "soaking", "soapier", "soapy", "soaring", "sober", "social", "socko", "sodden",
  "sodding", "soft", "softish", "soggy", "soiled", "sola", "solar", "sold", "sole", "soled", "solemn", "soli",
  "solid", "sollar", "solo", "soluble", "solus", "solute", "solved", "solvent", "somali", "somalia", "somatic",
  "somber", "sombre", "some", "sonant", "songful", "sonic", "sonless", "sonsie", "sonsy", "sooth", "soppier",
  "sopping", "soppy", "soprano", "sorbed", "sorbian", "sordid", "sore", "sorer", "sorest", "soritic", "sororal",
  "sorrel", "sorrier", "sorry", "sorted", "sothic", "sotted", "sottish", "sought", "soulful", "sound", "sounded",
  "soupier", "soupy", "sour", "soured", "sourish", "south", "soviet", "sovran", "sown", "sozzled", "spangly",
  "spanish", "spare", "sparid", "sparing", "sparkly", "sparoid", "sparry", "spartan", "spathic", "spatial", "spec",
  "special", "specked", "speedy", "spent", "sphenic", "spheral", "spheric", "sphery", "spidery", "spiffy", "spinal",
  "spindly", "spined", "spinier", "spinose", "spinous", "spiny", "spiral", "spirant", "spired", "spiroid", "spiry",
  "splashy", "splay", "spleeny", "splenic", "split", "splurgy", "spoiled", "spoilt", "spoken", "spongy", "spooky",
  "sport", "sporty", "spotted", "spotty", "spousal", "spouted", "sprawly", "spread", "spring", "springy", "spruce",
  "sprucer", "spry", "spryer", "spryest", "spumous", "spumy", "spun", "spurned", "spurred", "squeaky", "squint",
  "squirmy", "squishy", "stabbed", "stabile", "stable", "stacked", "staged", "stagier", "stagy", "staid", "stained",
  "stale", "stalked", "stalky", "stamped", "stannic", "staple", "stapled", "star", "starchy", "staring", "stark",
  "starlit", "starred", "starry", "starved", "statant", "state", "stated", "stately", "static", "statist", "stative",
  "statued", "statute", "staunch", "steady", "steamed", "stearic", "steely", "steep", "stelar", "stellar", "stemmed",
  "stereo", "steric", "sterile", "stern", "sternal", "stewed", "stey", "sthenic", "stibial", "stickit", "sticky",
  "stiff", "stifled", "still", "stilly", "stilted", "stingy", "stinko", "stinky", "stirred", "stock", "stocked",
  "stocky", "stodgy", "stoic", "stoical", "stolen", "stolid", "stone", "stonier", "stony", "stooped", "stopped",
  "store", "storied", "stormy", "stoss", "stout", "strait", "strange", "straw", "strawy", "stray", "streaky",
  "streamy", "stretch", "strewn", "striate", "strict", "stringy", "strip", "striped", "stripy", "strobic", "strong",
  "stroppy", "struck", "strung", "stubbly", "stubby", "stuck", "studded", "studied", "stuffed", "stuffy", "stumpy",
  "stung", "stunned", "stunted", "stupid", "sturdy", "stutter", "stygian", "stylar", "styled", "stylish", "styloid",
  "styptic", "suable", "suasory", "suave", "subacid", "subaqua", "subarid", "subdued", "suberic", "subfusc",
  "subject", "sublime", "submiss", "subtile", "subtle", "such", "suckled", "sudden", "sudsy", "suety", "sugared",
  "sugary", "suited", "sulcate", "sulfa", "sulkier", "sulkies", "sulky", "sullen", "sullied", "sulpha", "sultry",
  "summary", "summer", "summery", "sundry", "sunfast", "sung", "sunk", "sunken", "sunless", "sunlit", "sunnier",
  "sunny", "sunray", "sunrise", "sunset", "sunward", "super", "superb", "supine", "supple", "suppled", "suppler",
  "supreme", "sural", "surd", "sure", "surer", "surest", "surface", "surfy", "surging", "surgy", "surly", "surplus",
  "surreal", "suspect", "sutural", "svelte", "svelter", "swagger", "swamped", "swampy", "swaraj", "swart", "swarth",
  "swarthy", "swaying", "sweated", "sweaty", "swedish", "sweer", "sweet", "swell", "swelled", "sweltry", "swept",
  "swift", "swingy", "swinish", "swirly", "swish", "swishy", "swiss", "switch", "swollen", "sworn", "sylphic",
  "sylphid", "sylphy", "sylvan", "synodal", "synodic", "syrian", "syrupy", "tabby", "tabu", "tabular", "tacit",
  "tackier", "tacky", "tactful", "tactile", "tactual", "tagalog", "tagged", "tai", "tail", "tailed", "tailing",
  "tainted", "taken", "taking", "talc", "talcose", "taliped", "talking", "talky", "tall", "tallish", "tallowy",
  "taloned", "tamable", "tame", "tamed", "tamer", "tamest", "tamil", "taming", "tan", "tandem", "tangent", "tangier",
  "tangled", "tangy", "tanked", "tanned", "tannic", "taoism", "taoist", "taped", "tapered", "tapetal", "tapped",
  "tarmac", "tarnal", "tarot", "tarry", "tarsal", "tart", "tartish", "tasty", "tatar", "tatty", "taught", "taunt",
  "taurine", "taurus", "taut", "tawie", "tawney", "tawnier", "tawny", "taxable", "taxing", "tearful", "tearier",
  "tearing", "teary", "teased", "teasing", "techier", "techy", "tedious", "teeming", "teen", "teenage", "teenier",
  "teensy", "teentsy", "teeny", "tegular", "teind", "teleost", "telial", "telic", "telling", "telugu", "templed",
  "ten", "tenable", "tender", "tending", "tenfold", "tenor", "tense", "tensed", "tenser", "tensest", "tensile",
  "tensing", "tensive", "tented", "tenth", "tentie", "tentier", "tenty", "tenuous", "tenured", "tenuto", "tepid",
  "terbic", "terefah", "terete", "tergal", "ternary", "ternate", "terrene", "terse", "tertial", "tertian", "tertius",
  "test", "testate", "testy", "tetanic", "tetchy", "teuton", "textile", "textual", "thae", "thai", "thallic",
  "thawed", "thebaic", "theban", "thecal", "thecate", "theism", "theist", "then", "thenar", "therian", "thermal",
  "thermic", "thetic", "thick", "thin", "thinned", "third", "thirsty", "thirty", "thistly", "thomism", "thomist",
  "thraw", "thrawn", "thready", "three", "thrifty", "throaty", "through", "thrown", "thru", "thumbed", "thwart",
  "thymic", "thymy", "thyroid", "tiaraed", "tibetan", "tibial", "tidal", "tiddley", "tiddly", "tidied", "tidy",
  "tied", "tierced", "tight", "tiled", "tilled", "tilted", "timed", "timely", "timeous", "timid", "tin", "tinct",
  "tindery", "tineal", "tined", "tineid", "tinged", "tingly", "tinhorn", "tinier", "tiniest", "tinkly", "tinned",
  "tinnier", "tinny", "tinpot", "tinsel", "tinted", "tiny", "tipped", "tippier", "tippy", "tipsier", "tipsy",
  "tiptoe", "tiptop", "tired", "tiring", "toasted", "toe", "toed", "toeless", "toey", "togate", "togged", "toilful",
  "toiling", "told", "toltec", "toluic", "tomial", "tonal", "toned", "tonetic", "tongan", "tongued", "tonic",
  "tonier", "toniest", "tonish", "tonnish", "tony", "toom", "toothed", "toothy", "top", "topfull", "topiary",
  "topical", "topmost", "topped", "topping", "tops", "toric", "torn", "torose", "torpid", "torrent", "torrid",
  "tortile", "tory", "toryish", "tossing", "total", "totemic", "tother", "tottery", "touched", "touchy", "tough",
  "touring", "tourist", "tousled", "toward", "towered", "towery", "townish", "towy", "toxemic", "toxic", "toyless",
  "traced", "tracked", "trad", "trade", "traded", "tragic", "trained", "trapped", "trappy", "treacly", "treated",
  "treble", "treed", "treen", "tref", "trembly", "trendy", "trepid", "tressed", "tressy", "triable", "triacid",
  "triadic", "trial", "tribal", "tricksy", "tricky", "tricorn", "trident", "tried", "trifid", "triform", "trig",
  "trilled", "trim", "trimmed", "trinal", "trinary", "trine", "triple", "triste", "trite", "triter", "tritest",
  "triune", "trivial", "trochal", "trodden", "trophic", "tropic", "troppo", "troy", "truant", "true", "truer",
  "trussed", "trusted", "trusty", "trying", "tryptic", "tsarism", "tsarist", "tubal", "tubate", "tubbier", "tubby",
  "tubed", "tubular", "tucked", "tudor", "tufted", "tum", "tumid", "tumular", "tunable", "tuned", "tuneful", "tupian",
  "turbid", "turdine", "turfier", "turfy", "turgent", "turgid", "turki", "turkish", "turned", "turning", "tuscan",
  "tussal", "tussive", "tutelar", "tutored", "tutti", "twee", "tweedy", "twelfth", "twelve", "twenty", "twiggy",
  "twilit", "twill", "twilled", "twin", "twined", "twinned", "twisted", "twisty", "two", "twofold", "twp", "typal",
  "typed", "typhoid", "typhous", "typic", "typical", "tyrian", "ugandan", "ugly", "ugrian", "ugric", "ugsome",
  "ullaged", "ulnar", "ult", "ultimo", "ultra", "ululant", "umber", "umbonal", "umbral", "umbrian", "umbrose",
  "umpteen", "unable", "unacted", "unaided", "unaimed", "unaired", "unapt", "unarmed", "unary", "unasked", "unaware",
  "unawed", "unbaked", "unbated", "unbent", "unbid", "unblent", "unblown", "unborn", "unborne", "unbound", "unbowed",
  "unbred", "unbroke", "unburnt", "uncaged", "uncanny", "unchary", "uncial", "uncited", "uncivil", "unclad",
  "unclean", "unclear", "unco", "uncouth", "uncross", "uncured", "uncut", "undated", "undeaf", "undealt", "under",
  "undone", "undrawn", "undress", "undried", "undrunk", "undue", "undug", "undying", "uneasy", "uneaten", "unequal",
  "uneven", "unfaded", "unfair", "unfed", "unfelt", "unfiled", "unfine", "unfired", "unfirm", "unfit", "unfixed",
  "unfound", "unfree", "unfunny", "ungilt", "unglad", "ungodly", "ungored", "ungrown", "ungual", "unguled", "ungyved",
  "unhappy", "unhasty", "unheard", "unhewn", "unhired", "unholy", "unhoped", "unhuman", "unhung", "unhurt", "uniat",
  "unideal", "unific", "unified", "uniform", "union", "unique", "unitary", "united", "unitive", "unjaded", "unjust",
  "unkempt", "unkept", "unkind", "unknown", "unlaced", "unladen", "unlaid", "unled", "unlet", "unlimed", "unlined",
  "unlit", "unlost", "unloved", "unlucky", "unmade", "unmanly", "unmated", "unmeant", "unmeet", "unmet", "unmeted",
  "unmiry", "unmixed", "unmoral", "unmoved", "unmown", "unnamed", "unnoted", "unoiled", "unowned", "unpaced",
  "unpaged", "unpaid", "unpared", "unpaved", "unpent", "unplumb", "unposed", "unquiet", "unraked", "unrated",
  "unread", "unready", "unreal", "unrent", "unrimed", "unripe", "unrisen", "unriven", "unroped", "unrude", "unruled",
  "unruly", "unsafe", "unsaid", "unsated", "unsaved", "unseen", "unsent", "unset", "unshed", "unshod", "unshorn",
  "unshown", "unshut", "unsight", "unsized", "unslain", "unslung", "unsoft", "unsold", "unsolid", "unsonsy",
  "unsound", "unsown", "unspent", "unspied", "unspilt", "unspun", "unstack", "unstaid", "unstuck", "unsung",
  "unsunny", "unsure", "unsweet", "unswept", "unsworn", "untame", "untamed", "untaxed", "untidy", "untied", "untiled",
  "untired", "untold", "untoned", "untorn", "untried", "untrod", "untrue", "unurged", "unused", "unusual", "unvexed",
  "unvital", "unvocal", "unwaked", "unwary", "unweary", "unwed", "unwell", "unwept", "unwet", "unwiped", "unwired",
  "unwise", "unwitty", "unwon", "unwooed", "unworn", "unwound", "unwoven", "unwrung", "upbeat", "upbound", "upcast",
  "upended", "upgrade", "uphill", "upland", "upmost", "upper", "uppity", "upriver", "upscale", "upset", "upstage",
  "upstair", "upstart", "upstate", "uptight", "uptown", "upward", "upwind", "uraemia", "uralian", "uralic", "uranian",
  "uranic", "uranous", "urban", "urbane", "urdy", "uremic", "uretic", "urgent", "uric", "urinant", "urinary",
  "urinous", "urodele", "ursine", "usable", "useable", "used", "useful", "useless", "usual", "usurped", "uterine",
  "utile", "utility", "utmost", "utopian", "utter", "uttered", "uveal", "uveous", "uvular", "uxorial", "vacant",
  "vacuous", "vadose", "vain", "valgus", "valiant", "valid", "valued", "valval", "valvar", "valvate", "valved",
  "vaned", "vanward", "vapid", "vapory", "vapoury", "variant", "varied", "various", "varus", "varying", "vast",
  "vasty", "vatic", "vaulted", "vaunted", "vaunty", "veddoid", "vedic", "vee", "vegetal", "veiled", "veined",
  "veinier", "veiny", "velar", "velate", "vellum", "veloce", "velvet", "velvety", "venal", "venatic", "vendean",
  "venial", "venomed", "venose", "venous", "vented", "ventose", "ventral", "verbal", "verbose", "verdant", "verier",
  "veriest", "verism", "verist", "vernal", "versed", "very", "vesical", "vespine", "vestal", "vested", "vestral",
  "veteran", "vexed", "vexing", "viable", "vice", "vicinal", "vicious", "viewier", "viewy", "vile", "villose",
  "villous", "vinous", "vintage", "viny", "violate", "violent", "violet", "viral", "virgate", "virile", "virtual",
  "visaged", "viscid", "viscose", "viscous", "vishnu", "visible", "visored", "visual", "vital", "vitreum", "vitric",
  "vivace", "vivid", "vivo", "vocable", "vocal", "vocalic", "vogie", "vogue", "voguish", "voiced", "void", "voided",
  "volant", "volante", "volar", "voltaic", "voluble", "volumed", "volute", "voluted", "volvate", "vorant", "votary",
  "votive", "vulgar", "vulgate", "vulned", "vulpine", "vying", "wackier", "wacky", "wafd", "wafery", "waggish",
  "waggly", "wailful", "wailing", "waisted", "waiting", "wakeful", "waking", "wale", "walking", "walled", "walloon",
  "wally", "walnut", "wambly", "wan", "wandle", "waney", "wanier", "waniest", "waning", "wanner", "wannest",
  "wanning", "wannish", "wanted", "wanting", "wanton", "war", "warded", "ware", "warier", "wariest", "warm", "warmed",
  "warming", "warmish", "warning", "warped", "warring", "wartier", "warty", "wary", "washed", "washier", "washy",
  "waspier", "waspy", "waste", "wasted", "wasting", "watered", "watery", "wattle", "waugh", "waur", "waved", "wavier",
  "waviest", "waving", "wavy", "waxed", "waxen", "waxier", "waxiest", "waxing", "waxy", "wayless", "wayward",
  "wayworn", "weak", "weakly", "wealthy", "weaned", "wearied", "wearier", "wearing", "wearish", "weary", "weather",
  "weaving", "webbed", "webbier", "webby", "wed", "wedded", "wedged", "wedgy", "wee", "weeded", "weedier", "weedy",
  "weekday", "weekly", "weeny", "weepier", "weeping", "weepy", "weer", "weest", "weighty", "weird", "welcome",
  "welfare", "well", "welsh", "wendish", "wersh", "west", "western", "wet", "wetter", "wetting", "wettish", "whacked",
  "whacky", "wheaten", "wheeled", "wheezy", "whelked", "whelped", "wheyey", "whilom", "whinier", "whining", "whinny",
  "whiny", "whippy", "whist", "whole", "whorled", "wick", "wicked", "wicker", "wide", "wider", "widest", "widish",
  "widowed", "wieldy", "wifely", "wigged", "wiggly", "wight", "wigless", "wild", "wilful", "wilier", "wiliest",
  "willed", "willful", "willing", "willowy", "wilted", "wily", "wimpy", "winded", "windier", "winding", "windy",
  "winey", "winged", "winier", "winiest", "winking", "winning", "winsome", "winter", "wintery", "wintry", "winy",
  "wired", "wiretap", "wiring", "wiry", "wise", "wised", "wiser", "wisest", "wishful", "wising", "wispier", "wispy",
  "witchy", "withy", "witless", "witted", "wittier", "witting", "witty", "wizard", "wizen", "wizened", "woaded",
  "wobbly", "woeful", "woesome", "wolfish", "womanly", "wombed", "won", "wonky", "wonted", "wood", "wooded", "wooden",
  "woodier", "woods", "woodsy", "woody", "woolen", "woollen", "woolly", "woozier", "woozy", "wordier", "wordy",
  "worked", "working", "world", "worldly", "wormy", "worn", "worried", "worse", "worser", "worst", "worth", "worthy",
  "wound", "wounded", "woven", "wrapped", "wrath", "wrecked", "wrier", "wriest", "wriggly", "wrinkly", "writhed",
  "writhen", "written", "wrong", "wronged", "wroth", "wrought", "wry", "wud", "xanthic", "xerarch", "xeric",
  "xiphoid", "xylic", "xyloid", "yare", "yarer", "yarest", "yauld", "yawning", "yclept", "yearly", "yeld", "yelled",
  "yelling", "yellow", "yemen", "yester", "yestern", "yogic", "yolky", "yon", "yonder", "yorkist", "yoruban", "young",
  "younger", "yttric", "yucky", "yummy", "zairean", "zanier", "zanies", "zaniest", "zany", "zealous", "zebrine",
  "zesty", "zig", "zigzag", "zillion", "zincky", "zincoid", "zincous", "zincy", "zingy", "zinky", "zionism",
  "zionist", "zippy", "zoic", "zonal", "zonary", "zonate", "zoning", "zonked", "zonular", "zoonal", "zygotic",
  "zymotic", "zyrian"];
